import type { Contact } from './contacts.utils';

export const CONTACTS: Contact[] = [
  {
    id: 1,
    av: '王',
    g: 'linear-gradient(135deg,#60a5fa,#2563eb)',
    nm: '王俊傑',
    title: '採購部協理',
    role: '決策者',
    co: 'tsmc',
    pri: true,
    owner: 'zhang',
    email: 'jj.wang@tsmc.com',
    phone: '03-5636688 #2201',
    mobile: '0912-345-678',
    last: '電話會議',
    ago: '2 小時前',
    opps: [
      { nm: '2026 智慧製造平台導入', stage: 'negotiate', stageL: '議約談判', amt: 'NT$ 2.4M' },
      { nm: '年度技術支援續約', stage: 'need', stageL: '需求分析', amt: 'NT$ 0.6M' },
    ],
    acts: [
      {
        t: 'call',
        ti: '電話會議',
        d: '確認智慧製造平台導入時程，對方希望 Q3 完成 POC。',
        m: '張志豪 · 2 小時前',
      },
      {
        t: 'mail',
        ti: '寄送會議紀要',
        d: '整理上週技術討論重點與待辦清單。',
        m: '張志豪 · 3 天前',
      },
    ],
  },
  {
    id: 2,
    av: '李',
    g: 'linear-gradient(135deg,#34D399,#10b981)',
    nm: '李欣怡',
    title: '資訊處經理',
    role: '技術窗口',
    co: 'tsmc',
    pri: false,
    owner: 'zhang',
    email: 'hy.lee@tsmc.com',
    phone: '03-5636688 #3310',
    mobile: '0922-118-220',
    last: 'Email 往來',
    ago: '昨天',
    opps: [{ nm: '資安監控系統擴充', stage: 'proposal', stageL: '提案報價', amt: 'NT$ 1.2M' }],
    acts: [
      { t: 'mail', ti: '技術規格確認', d: '回覆資安監控系統的整合介面問題。', m: '張志豪 · 昨天' },
    ],
  },
  {
    id: 3,
    av: '陳',
    g: 'linear-gradient(135deg,#fbbf24,#f59e0b)',
    nm: '陳冠宇',
    title: '營運副總',
    role: '決策者',
    co: 'fox',
    pri: true,
    owner: 'lin',
    email: 'gy.chen@foxconn.com',
    phone: '02-22683466 #1100',
    mobile: '0918-660-330',
    last: '季度會議',
    ago: '1 天前',
    opps: [{ nm: '供應鏈管理系統升級', stage: 'proposal', stageL: '提案報價', amt: 'NT$ 2.0M' }],
    acts: [
      {
        t: 'meet',
        ti: '季度業務檢視會議',
        d: '回顧上半年導入進度，確認下半年擴點計畫。',
        m: '林俊傑 · 1 天前',
      },
    ],
  },
  {
    id: 4,
    av: '吳',
    g: 'linear-gradient(135deg,#60a5fa,#2563eb)',
    nm: '吳孟潔',
    title: '採購經理',
    role: '採購窗口',
    co: 'fox',
    pri: false,
    owner: 'lin',
    email: 'mj.wu@foxconn.com',
    phone: '02-22683466 #1180',
    mobile: '0935-221-447',
    last: '報價討論',
    ago: '4 天前',
    opps: [{ nm: '倉儲自動化整合案', stage: 'need', stageL: '需求分析', amt: 'NT$ 1.1M' }],
    acts: [
      {
        t: 'note',
        ti: '新增備註',
        d: '採購流程需經三層審核，預留兩週緩衝。',
        m: '林俊傑 · 4 天前',
      },
    ],
  },
  {
    id: 5,
    av: '林',
    g: 'linear-gradient(135deg,#a78bfa,#7c3aed)',
    nm: '林佳蓉',
    title: '技術採購總監',
    role: '決策者',
    co: 'mtk',
    pri: true,
    owner: 'chen',
    email: 'jr.lin@mediatek.com',
    phone: '03-5670766 #4400',
    mobile: '0910-882-156',
    last: '合約協商',
    ago: '5 小時前',
    opps: [{ nm: '雲端研發環境建置', stage: 'negotiate', stageL: '議約談判', amt: 'NT$ 1.8M' }],
    acts: [
      {
        t: 'call',
        ti: '合約條款協商',
        d: '對方要求 SLA 提升至 99.9%，已回報主管評估。',
        m: '陳美華 · 5 小時前',
      },
    ],
  },
  {
    id: 6,
    av: '黃',
    g: 'linear-gradient(135deg,#34D399,#10b981)',
    nm: '黃信宏',
    title: 'IT 基礎架構經理',
    role: '技術窗口',
    co: 'mtk',
    pri: false,
    owner: 'chen',
    email: 'sh.huang@mediatek.com',
    phone: '03-5670766 #4520',
    mobile: '0978-330-661',
    last: 'POC 回報',
    ago: '2 天前',
    opps: [{ nm: '資料分析平台導入', stage: 'proposal', stageL: '提案報價', amt: 'NT$ 1.0M' }],
    acts: [
      { t: 'mail', ti: '寄送 POC 結果', d: '資料分析平台查詢效能提升 40%。', m: '陳美華 · 2 天前' },
    ],
  },
  {
    id: 7,
    av: '黃',
    g: 'linear-gradient(135deg,#34D399,#10b981)',
    nm: '黃柏翰',
    title: '數位轉型處長',
    role: '決策者',
    co: 'delta',
    pri: true,
    owner: 'chen',
    email: 'ph.huang@deltaww.com',
    phone: '03-3626301 #500',
    mobile: '0926-771-308',
    last: 'Demo 簡報',
    ago: '6 小時前',
    opps: [{ nm: '能源管理儀表板專案', stage: 'proposal', stageL: '提案報價', amt: 'NT$ 0.9M' }],
    acts: [
      {
        t: 'mail',
        ti: '寄送能源儀表板 Demo',
        d: '處長對即時能耗視覺化反應正面。',
        m: '陳美華 · 6 小時前',
      },
    ],
  },
  {
    id: 8,
    av: '劉',
    g: 'linear-gradient(135deg,#22d3ee,#0891b2)',
    nm: '劉雅琪',
    title: '採購中心總監',
    role: '決策者',
    co: 'asus',
    pri: true,
    owner: 'zhang',
    email: 'yc.liu@asus.com',
    phone: '02-28943447 #700',
    mobile: '0913-558-902',
    last: '成交慶功',
    ago: '4 小時前',
    opps: [
      { nm: '全球客服系統整合', stage: 'won', stageL: '已成交', amt: 'NT$ 1.5M' },
      { nm: 'AI 客服機器人擴充', stage: 'proposal', stageL: '提案報價', amt: 'NT$ 0.6M' },
    ],
    acts: [
      {
        t: 'meet',
        ti: '成交慶功與後續規劃',
        d: '全球客服系統正式上線，討論 AI 客服第二期合作。',
        m: '張志豪 · 4 小時前',
      },
    ],
  },
];
