import type { Account } from './accounts.utils';

export const ACCOUNTS: Account[] = [
  {
    id: 1,
    logo: '台',
    lg: 'linear-gradient(135deg,#2563eb,#1e3a5f)',
    name: '台積電',
    star: true,
    domain: 'tsmc.com',
    ind: '半導體',
    size: '73,000+ 人',
    sizeShort: '73,000+',
    amt: 'NT$ 4.2M',
    oppN: 3,
    owner: 'zhang',
    health: 'good',
    info: {
      stat: '22099131',
      web: 'tsmc.com',
      phone: '03-5636688',
      addr: '新竹市力行六路 8 號',
      region: '新竹',
      since: '2023 年 11 月',
    },
    age: '2.4 年',
    contacts: [
      {
        nm: '王俊傑',
        title: '採購部協理',
        pri: true,
        g: 'linear-gradient(135deg,#60a5fa,#2563eb)',
        av: '王',
      },
      { nm: '李欣怡', title: '資訊處經理', g: 'linear-gradient(135deg,#34D399,#10b981)', av: '李' },
      { nm: '張庭瑋', title: '供應鏈專員', g: 'linear-gradient(135deg,#a78bfa,#7c3aed)', av: '張' },
    ],
    opps: [
      {
        nm: '2026 智慧製造平台導入',
        stage: 'negotiate',
        stageL: '議約談判',
        close: '2026/07/30',
        amt: 'NT$ 2.4M',
      },
      {
        nm: '資安監控系統擴充',
        stage: 'proposal',
        stageL: '提案報價',
        close: '2026/08/15',
        amt: 'NT$ 1.2M',
      },
      {
        nm: '年度技術支援續約',
        stage: 'need',
        stageL: '需求分析',
        close: '2026/09/10',
        amt: 'NT$ 0.6M',
      },
    ],
    acts: [
      {
        t: 'call',
        ti: '與王協理電話會議',
        d: '確認智慧製造平台導入時程，對方希望 Q3 完成 POC。',
        m: '張志豪 · 2 小時前',
      },
      {
        t: 'mail',
        ti: '寄送提案報價單',
        d: '資安監控系統擴充 — 報價 NT$ 1.2M，已附導入時程表。',
        m: '張志豪 · 昨天',
      },
      {
        t: 'meet',
        ti: '現場需求訪談',
        d: '與資訊處 3 位窗口討論年度技術支援範圍。',
        m: '陳美華 · 3 天前',
      },
    ],
  },
  {
    id: 2,
    logo: '鴻',
    lg: 'linear-gradient(135deg,#1e3a5f,#122440)',
    name: '鴻海精密',
    star: false,
    domain: 'foxconn.com',
    ind: '電子製造',
    size: '80,000+ 人',
    sizeShort: '80,000+',
    amt: 'NT$ 3.1M',
    oppN: 2,
    owner: 'lin',
    health: 'stable',
    info: {
      stat: '04541302',
      web: 'foxconn.com',
      phone: '02-22683466',
      addr: '新北市土城區自由街 2 號',
      region: '新北',
      since: '2024 年 03 月',
    },
    age: '2.1 年',
    contacts: [
      {
        nm: '陳冠宇',
        title: '營運副總',
        pri: true,
        g: 'linear-gradient(135deg,#fbbf24,#f59e0b)',
        av: '陳',
      },
      { nm: '吳孟潔', title: '採購經理', g: 'linear-gradient(135deg,#60a5fa,#2563eb)', av: '吳' },
    ],
    opps: [
      {
        nm: '供應鏈管理系統升級',
        stage: 'proposal',
        stageL: '提案報價',
        close: '2026/08/05',
        amt: 'NT$ 2.0M',
      },
      {
        nm: '倉儲自動化整合案',
        stage: 'need',
        stageL: '需求分析',
        close: '2026/09/22',
        amt: 'NT$ 1.1M',
      },
    ],
    acts: [
      {
        t: 'meet',
        ti: '季度業務檢視會議',
        d: '回顧上半年導入進度，雙方確認下半年擴點計畫。',
        m: '林俊傑 · 1 天前',
      },
      {
        t: 'note',
        ti: '新增備註',
        d: '對方資安政策嚴格，導入需經三層審核，預留兩週緩衝。',
        m: '林俊傑 · 4 天前',
      },
    ],
  },
  {
    id: 3,
    logo: '聯',
    lg: 'linear-gradient(135deg,#7c3aed,#5b21b6)',
    name: '聯發科技',
    star: true,
    domain: 'mediatek.com',
    ind: 'IC 設計',
    size: '19,000+ 人',
    sizeShort: '19,000+',
    amt: 'NT$ 2.8M',
    oppN: 2,
    owner: 'chen',
    health: 'good',
    info: {
      stat: '23100417',
      web: 'mediatek.com',
      phone: '03-5670766',
      addr: '新竹市篤行一路 1 號',
      region: '新竹',
      since: '2023 年 06 月',
    },
    age: '3.0 年',
    contacts: [
      {
        nm: '林佳蓉',
        title: '技術採購總監',
        pri: true,
        g: 'linear-gradient(135deg,#a78bfa,#7c3aed)',
        av: '林',
      },
      {
        nm: '黃信宏',
        title: 'IT 基礎架構經理',
        g: 'linear-gradient(135deg,#34D399,#10b981)',
        av: '黃',
      },
    ],
    opps: [
      {
        nm: '雲端研發環境建置',
        stage: 'negotiate',
        stageL: '議約談判',
        close: '2026/07/18',
        amt: 'NT$ 1.8M',
      },
      {
        nm: '資料分析平台導入',
        stage: 'proposal',
        stageL: '提案報價',
        close: '2026/08/28',
        amt: 'NT$ 1.0M',
      },
    ],
    acts: [
      {
        t: 'call',
        ti: '合約條款協商',
        d: '雲端研發環境 — 對方要求 SLA 提升至 99.9%，已回報主管評估。',
        m: '陳美華 · 5 小時前',
      },
      {
        t: 'mail',
        ti: '寄送 POC 結果報告',
        d: '資料分析平台試行成效良好，查詢效能提升 40%。',
        m: '陳美華 · 2 天前',
      },
    ],
  },
  {
    id: 4,
    logo: '緯',
    lg: 'linear-gradient(135deg,#0ea5e9,#0369a1)',
    name: '緯創資通',
    star: false,
    domain: 'wistron.com',
    ind: '電子製造',
    size: '1,000+ 人',
    sizeShort: '1,000+',
    amt: 'NT$ 0.9M',
    oppN: 1,
    owner: 'zhang',
    health: 'watch',
    info: {
      stat: '16668113',
      web: 'wistron.com',
      phone: '02-66128000',
      addr: '台北市內湖區瑞光路 158 號',
      region: '台北',
      since: '2026 年 06 月',
    },
    age: '14 天',
    contacts: [
      {
        nm: '陳雅婷',
        title: '採購經理',
        pri: true,
        g: 'linear-gradient(135deg,#f87171,#dc2626)',
        av: '陳',
      },
    ],
    opps: [
      {
        nm: '緯創資通 — 新商機',
        stage: 'need',
        stageL: '需求分析',
        close: '2026/07/15',
        amt: 'NT$ 0.9M',
      },
    ],
    acts: [
      {
        t: 'note',
        ti: '由潛客轉換建立',
        d: '自潛在客戶「陳雅婷」一鍵轉換，已建立帳號、聯絡人與商機。',
        m: '陳小明 · 剛剛',
      },
      {
        t: 'call',
        ti: '初次需求電訪',
        d: '了解採購規模與導入時程，對方仍在比較階段，需積極跟進。',
        m: '張志豪 · 1 天前',
      },
    ],
  },
  {
    id: 5,
    logo: '台',
    lg: 'linear-gradient(135deg,#dc2626,#991b1b)',
    name: '台達電子',
    star: false,
    domain: 'deltaww.com',
    ind: '電源管理',
    size: '10,000+ 人',
    sizeShort: '10,000+',
    amt: 'NT$ 1.4M',
    oppN: 2,
    owner: 'chen',
    health: 'stable',
    info: {
      stat: '22018156',
      web: 'deltaww.com',
      phone: '03-3626301',
      addr: '桃園市龜山區興邦路 31-1 號',
      region: '桃園',
      since: '2024 年 09 月',
    },
    age: '1.8 年',
    contacts: [
      {
        nm: '黃柏翰',
        title: '數位轉型處長',
        pri: true,
        g: 'linear-gradient(135deg,#34D399,#10b981)',
        av: '黃',
      },
      { nm: '蘇怡君', title: '採購副理', g: 'linear-gradient(135deg,#60a5fa,#2563eb)', av: '蘇' },
    ],
    opps: [
      {
        nm: '能源管理儀表板專案',
        stage: 'proposal',
        stageL: '提案報價',
        close: '2026/08/12',
        amt: 'NT$ 0.9M',
      },
      {
        nm: 'IoT 設備監控擴充',
        stage: 'need',
        stageL: '需求分析',
        close: '2026/09/30',
        amt: 'NT$ 0.5M',
      },
    ],
    acts: [
      {
        t: 'mail',
        ti: '寄送能源儀表板 Demo',
        d: '處長對即時能耗視覺化反應正面，下週安排內部簡報。',
        m: '陳美華 · 6 小時前',
      },
      {
        t: 'meet',
        ti: '導入啟動會議',
        d: '確認專案範圍與里程碑，雙方 PM 已建立溝通群組。',
        m: '陳美華 · 3 天前',
      },
    ],
  },
  {
    id: 6,
    logo: '研',
    lg: 'linear-gradient(135deg,#059669,#047857)',
    name: '研華科技',
    star: false,
    domain: 'advantech.com',
    ind: '工業電腦',
    size: '8,000+ 人',
    sizeShort: '8,000+',
    amt: 'NT$ 0',
    oppN: 0,
    owner: 'lin',
    health: 'risk',
    info: {
      stat: '25081353',
      web: 'advantech.com',
      phone: '02-27927818',
      addr: '台北市內湖區瑞光路 26 巷',
      region: '台北',
      since: '2023 年 02 月',
    },
    age: '3.3 年',
    contacts: [
      {
        nm: '林志明',
        title: '資訊部協理',
        pri: true,
        g: 'linear-gradient(135deg,#fbbf24,#f59e0b)',
        av: '林',
      },
    ],
    opps: [],
    acts: [
      {
        t: 'note',
        ti: '標記為風險帳號',
        d: '近 90 天無互動，原合約已到期未續，需主管介入挽回。',
        m: '林俊傑 · 1 週前',
      },
      {
        t: 'call',
        ti: '續約跟進未接',
        d: '撥打協理手機未接，已留言並改寄 Email。',
        m: '林俊傑 · 2 週前',
      },
    ],
  },
  {
    id: 7,
    logo: '華',
    lg: 'linear-gradient(135deg,#0891b2,#0e7490)',
    name: '華碩電腦',
    star: true,
    domain: 'asus.com',
    ind: '消費電子',
    size: '15,000+ 人',
    sizeShort: '15,000+',
    amt: 'NT$ 2.1M',
    oppN: 2,
    owner: 'zhang',
    health: 'good',
    info: {
      stat: '23638577',
      web: 'asus.com',
      phone: '02-28943447',
      addr: '台北市北投區立德路 15 號',
      region: '台北',
      since: '2022 年 12 月',
    },
    age: '3.5 年',
    contacts: [
      {
        nm: '劉雅琪',
        title: '採購中心總監',
        pri: true,
        g: 'linear-gradient(135deg,#22d3ee,#0891b2)',
        av: '劉',
      },
      {
        nm: '鄭凱文',
        title: '系統整合經理',
        g: 'linear-gradient(135deg,#a78bfa,#7c3aed)',
        av: '鄭',
      },
    ],
    opps: [
      {
        nm: '全球客服系統整合',
        stage: 'won',
        stageL: '已成交',
        close: '2026/06/01',
        amt: 'NT$ 1.5M',
      },
      {
        nm: 'AI 客服機器人擴充',
        stage: 'proposal',
        stageL: '提案報價',
        close: '2026/08/20',
        amt: 'NT$ 0.6M',
      },
    ],
    acts: [
      {
        t: 'meet',
        ti: '成交慶功與後續規劃',
        d: '全球客服系統正式上線，討論 AI 客服第二期合作意向。',
        m: '張志豪 · 4 小時前',
      },
      {
        t: 'mail',
        ti: '寄送上線成效報告',
        d: '客服回應時間縮短 35%，滿意度提升至 4.6 分。',
        m: '張志豪 · 昨天',
      },
    ],
  },
];
