import type { RoleKey, UserData } from './settings.types';

export const ROLES: Record<RoleKey, { name: string; color: string; cap: number; over: string }> = {
  admin: { name: '系統管理員', color: '#2563eb', cap: 100, over: 'unlimited' },
  director: { name: '區域總監', color: '#6d28d9', cap: 40, over: 'approve' },
  manager: { name: '業務經理', color: '#0891b2', cap: 25, over: 'approve' },
  senior: { name: '資深業務', color: '#059669', cap: 15, over: 'approve' },
  rep: { name: '業務代表', color: '#ea7a1e', cap: 10, over: 'approve' },
  support: { name: '業務支援', color: '#9aa1ae', cap: 0, over: 'block' },
};

export const USERS: UserData[] = [
  {
    av: '陳',
    g: 'green',
    name: '陳小明',
    email: 'chen.xm@cxcrm.com',
    title: '資深業務經理',
    role: 'manager',
    profile: '業務經理',
    perms: ['報表匯出', '商機刪除'],
    status: 'active',
    last: '2 小時前',
    since: '2023/11/04',
  },
  {
    av: '王',
    g: 'navy',
    name: '王淑芬',
    email: 'wang.sf@cxcrm.com',
    title: 'IT 系統管理員',
    role: 'admin',
    profile: '系統管理員',
    perms: ['報表匯出', '商機刪除', 'API 存取', '大量匯入精靈', 'Cisco 整合'],
    status: 'active',
    last: '剛剛',
    since: '2022/08/15',
  },
  {
    av: '李',
    g: 'cyan',
    name: '李孟翰',
    email: 'lee.mh@cxcrm.com',
    title: '北區區域總監',
    role: 'director',
    profile: '業務經理',
    perms: ['報表匯出', 'API 存取'],
    status: 'active',
    last: '1 天前',
    since: '2023/02/20',
  },
  {
    av: '陳',
    g: 'violet',
    name: '陳美華',
    email: 'chen.mh@cxcrm.com',
    title: '資深業務',
    role: 'senior',
    profile: '標準業務',
    perms: ['報表匯出', '大量匯入精靈'],
    status: 'active',
    last: '3 小時前',
    since: '2023/06/11',
  },
  {
    av: '張',
    g: 'blue',
    name: '張志豪',
    email: 'chang.zh@cxcrm.com',
    title: '業務代表',
    role: 'rep',
    profile: '標準業務',
    perms: ['報表匯出'],
    status: 'active',
    last: '昨天',
    since: '2024/03/01',
  },
  {
    av: '林',
    g: 'amber',
    name: '林俊傑',
    email: 'lin.cj@cxcrm.com',
    title: '業務代表',
    role: 'rep',
    profile: '標準業務',
    perms: [],
    status: 'active',
    last: '5 天前',
    since: '2024/09/18',
  },
  {
    av: '吳',
    g: 'teal',
    name: '吳建宏',
    email: 'wu.jh@cxcrm.com',
    title: '資深業務',
    role: 'senior',
    profile: '標準業務',
    perms: ['Cisco 整合'],
    status: 'pending',
    last: '—',
    since: '2026/06/14',
  },
  {
    av: '黃',
    g: 'rose',
    name: '黃詩涵',
    email: 'huang.sh@cxcrm.com',
    title: '業務支援專員',
    role: 'support',
    profile: '業務支援',
    perms: [],
    status: 'inactive',
    last: '30 天前',
    since: '2023/01/09',
  },
];
