import type {
  RoleKey,
  UserData,
  RoleNode,
  RPerson,
  FlowTrig,
  FlowItem,
  RunEntry,
  VerEntry,
  ImpSrc,
  ImpStatus,
  BatchItem,
  ImpErrEntry,
  MapRow,
  ImpRecEntry,
  ProfileData,
  PermSetData,
  ObjItem,
} from './settings.types';

import type { EmailCategory, EmailSig, EmailTemplate, EmailMergeGroup } from './email.utils';
import type { PLPaletteTab, PLPaletteGroup, PLSection, PLRelCard } from './pagelayout.utils';

// Profile 物件存取矩陣用的物件清單與各存取層級的權限格（DetailDrawer ProfileContent 用）。
export const OBJECTS = [
  { nm: '客戶帳號', api: 'Account' },
  { nm: '聯絡人', api: 'Contact' },
  { nm: '商機', api: 'Opportunity' },
  { nm: '潛在客戶', api: 'Lead' },
  { nm: '活動 / 任務', api: 'Activity' },
  { nm: '報表', api: 'Report' },
];
export const ACCESS: Record<string, boolean[][]> = {
  full: OBJECTS.map(() => [true, true, true, true]),
  rw: [
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 0],
  ].map((r) => r.map(Boolean)),
  std: [
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [1, 0, 0, 0],
  ].map((r) => r.map(Boolean)),
  support: [
    [1, 0, 1, 0],
    [1, 1, 1, 0],
    [1, 0, 0, 0],
    [1, 1, 1, 0],
    [1, 1, 1, 0],
    [1, 0, 0, 0],
  ].map((r) => r.map(Boolean)),
  ro: OBJECTS.map(() => [true, false, false, false]),
};

// 物件管理員圖示底色樣式（依 g 色鍵；ObjectsPanel 與 FieldsPanel 共用）。
export const OBJ_ICON_STYLE: Record<string, { bg: string; color: string }> = {
  blue: { bg: 'var(--cx-accent-soft)', color: 'var(--cx-accent)' },
  green: { bg: 'var(--cx-success-soft)', color: '#059669' },
  violet: { bg: '#EDE9FE', color: '#6d28d9' },
  amber: { bg: '#FEF3C7', color: '#b45309' },
  cyan: { bg: '#E0F2FE', color: '#0369a1' },
  teal: { bg: '#CCFBF1', color: '#0d9488' },
};

// 物件管理員清單資料（shell setActiveTab、ObjectsPanel、FieldsPanel 共用）。
export const OBJ_ITEMS: ObjItem[] = [
  {
    nm: '客戶帳號',
    api: 'Account',
    icon: '帳',
    g: 'blue',
    records: 1248,
    fields: 148,
    std: true,
    customFields: 12,
  },
  {
    nm: '聯絡人',
    api: 'Contact',
    icon: '聯',
    g: 'green',
    records: 3902,
    fields: 62,
    std: true,
    customFields: 5,
  },
  {
    nm: '商機',
    api: 'Opportunity',
    icon: '機',
    g: 'violet',
    records: 846,
    fields: 54,
    std: true,
    customFields: 8,
  },
  {
    nm: '潛在客戶',
    api: 'Lead',
    icon: '潛',
    g: 'amber',
    records: 312,
    fields: 43,
    std: true,
    customFields: 3,
  },
  {
    nm: '報價單',
    api: 'Quote__c',
    icon: '報',
    g: 'cyan',
    records: 1205,
    fields: 28,
    std: false,
    customFields: 28,
  },
  {
    nm: '服務合約',
    api: 'ServiceContract__c',
    icon: '約',
    g: 'teal',
    records: 420,
    fields: 22,
    std: false,
    customFields: 22,
  },
];

// 使用者/紀錄狀態 → CSS class 與顯示標籤（由 StatusBadge 與 shell 共用）。
export const STATUS_MAP = {
  active: { cls: 'active', lbl: '啟用中' },
  inactive: { cls: 'inactive', lbl: '停用' },
  pending: { cls: 'pending', lbl: '待啟用' },
};

// 頭像漸層底色（依 g 色鍵）。
export const GRAD: Record<string, string> = {
  green: 'linear-gradient(135deg,#34D399,#10b981)',
  blue: 'linear-gradient(135deg,#60a5fa,#2563eb)',
  violet: 'linear-gradient(135deg,#a78bfa,#7c3aed)',
  amber: 'linear-gradient(135deg,#fbbf24,#f59e0b)',
  navy: 'linear-gradient(135deg,#3b82f6,#1e3a5f)',
  cyan: 'linear-gradient(135deg,#22d3ee,#0891b2)',
  rose: 'linear-gradient(135deg,#f87171,#dc2626)',
  teal: 'linear-gradient(135deg,#2dd4bf,#0d9488)',
};

export const ROLES: Record<RoleKey, { name: string; color: string; cap: number; over: string }> = {
  admin: { name: '系統管理員', color: '#2563eb', cap: 100, over: 'unlimited' },
  director: { name: '區域總監', color: '#6d28d9', cap: 40, over: 'approve' },
  manager: { name: '業務經理', color: '#0891b2', cap: 25, over: 'approve' },
  senior: { name: '資深業務', color: '#059669', cap: 15, over: 'approve' },
  rep: { name: '業務代表', color: '#ea7a1e', cap: 10, over: 'approve' },
  support: { name: '業務支援', color: '#9aa1ae', cap: 0, over: 'block' },
};

export const USERS: UserData[] = [
  {
    av: '陳',
    g: 'green',
    name: '陳小明',
    email: 'chen.xm@cxcrm.com',
    title: '資深業務經理',
    role: 'manager',
    profile: '業務經理',
    perms: ['報表匯出', '商機刪除'],
    status: 'active',
    last: '2 小時前',
    since: '2023/11/04',
  },
  {
    av: '王',
    g: 'navy',
    name: '王淑芬',
    email: 'wang.sf@cxcrm.com',
    title: 'IT 系統管理員',
    role: 'admin',
    profile: '系統管理員',
    perms: ['報表匯出', '商機刪除', 'API 存取', '大量匯入精靈', 'Cisco 整合'],
    status: 'active',
    last: '剛剛',
    since: '2022/08/15',
  },
  {
    av: '李',
    g: 'cyan',
    name: '李孟翰',
    email: 'lee.mh@cxcrm.com',
    title: '北區區域總監',
    role: 'director',
    profile: '業務經理',
    perms: ['報表匯出', 'API 存取'],
    status: 'active',
    last: '1 天前',
    since: '2023/02/20',
  },
  {
    av: '陳',
    g: 'violet',
    name: '陳美華',
    email: 'chen.mh@cxcrm.com',
    title: '資深業務',
    role: 'senior',
    profile: '標準業務',
    perms: ['報表匯出', '大量匯入精靈'],
    status: 'active',
    last: '3 小時前',
    since: '2023/06/11',
  },
  {
    av: '張',
    g: 'blue',
    name: '張志豪',
    email: 'chang.zh@cxcrm.com',
    title: '業務代表',
    role: 'rep',
    profile: '標準業務',
    perms: ['報表匯出'],
    status: 'active',
    last: '昨天',
    since: '2024/03/01',
  },
  {
    av: '林',
    g: 'amber',
    name: '林俊傑',
    email: 'lin.cj@cxcrm.com',
    title: '業務代表',
    role: 'rep',
    profile: '標準業務',
    perms: [],
    status: 'active',
    last: '5 天前',
    since: '2024/09/18',
  },
  {
    av: '吳',
    g: 'teal',
    name: '吳建宏',
    email: 'wu.jh@cxcrm.com',
    title: '資深業務',
    role: 'senior',
    profile: '標準業務',
    perms: ['Cisco 整合'],
    status: 'pending',
    last: '—',
    since: '2026/06/14',
  },
  {
    av: '黃',
    g: 'rose',
    name: '黃詩涵',
    email: 'huang.sh@cxcrm.com',
    title: '業務支援專員',
    role: 'support',
    profile: '業務支援',
    perms: [],
    status: 'inactive',
    last: '30 天前',
    since: '2023/01/09',
  },
];

// ── Roles 資料 ────────────────────────────────────────────────────────────────
export const ORG_NAME = 'CX CRM 股份有限公司';

export const ROLE_HIER: RoleNode[] = [
  { name: '客戶成功經理', code: 'CSM', color: '#0891b2' },
  { name: '續約經理', code: 'Renewal_Mgr', color: '#7c3aed' },
  { name: '產品經理', code: 'Product_Mgr', color: '#db2777' },
  {
    name: '業務主管',
    code: 'Sales_Lead',
    color: '#2563eb',
    children: [
      {
        name: '業務組長',
        code: 'Sales_TeamLead',
        color: '#0d9488',
        children: [{ name: '業務人員', code: 'Sales_Staff', color: '#059669' }],
      },
    ],
  },
  { name: '業務代表', code: 'Sales_Rep', color: '#ea7a1e' },
  { name: '技術顧問', code: 'Tech_Consult', color: '#6d28d9' },
];

export const RPEOPLE_INIT: RPerson[] = [
  {
    av: '林',
    g: 'rose',
    name: '林雅婷',
    title: '客戶成功資深專員',
    email: 'lin.yt@cxcrm.com',
    role: '客戶成功經理',
  },
  {
    av: '周',
    g: 'blue',
    name: '周冠宇',
    title: '客戶成功經理',
    email: 'chou.gy@cxcrm.com',
    role: '客戶成功經理',
  },
  {
    av: '蔡',
    g: 'violet',
    name: '蔡岱穎',
    title: '續約業務經理',
    email: 'tsai.dy@cxcrm.com',
    role: '續約經理',
  },
  {
    av: '鄭',
    g: 'cyan',
    name: '鄭凱文',
    title: '產品線經理',
    email: 'cheng.kw@cxcrm.com',
    role: '產品經理',
  },
  {
    av: '高',
    g: 'amber',
    name: '高敏華',
    title: '產品企劃經理',
    email: 'kao.mh@cxcrm.com',
    role: '產品經理',
  },
  {
    av: '李',
    g: 'navy',
    name: '李孟翰',
    title: '北區業務主管',
    email: 'lee.mh@cxcrm.com',
    role: '業務主管',
  },
  {
    av: '陳',
    g: 'green',
    name: '陳小明',
    title: '業務一組組長',
    email: 'chen.xm@cxcrm.com',
    role: '業務組長',
  },
  {
    av: '吳',
    g: 'teal',
    name: '吳建宏',
    title: '業務二組組長',
    email: 'wu.jh@cxcrm.com',
    role: '業務組長',
  },
  {
    av: '張',
    g: 'blue',
    name: '張志豪',
    title: '業務專員',
    email: 'chang.zh@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '林',
    g: 'amber',
    name: '林俊傑',
    title: '業務專員',
    email: 'lin.cj@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '黃',
    g: 'rose',
    name: '黃詩涵',
    title: '業務專員',
    email: 'huang.sh@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '許',
    g: 'cyan',
    name: '許文彥',
    title: '業務專員',
    email: 'hsu.wy@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '劉',
    g: 'violet',
    name: '劉哲瑋',
    title: '業務代表',
    email: 'liu.zw@cxcrm.com',
    role: '業務代表',
  },
  {
    av: '楊',
    g: 'teal',
    name: '楊雅筑',
    title: '業務代表',
    email: 'yang.yz@cxcrm.com',
    role: '業務代表',
  },
  {
    av: '簡',
    g: 'green',
    name: '簡上瑋',
    title: '業務代表',
    email: 'chien.sw@cxcrm.com',
    role: '業務代表',
  },
  {
    av: '范',
    g: 'navy',
    name: '范柏宏',
    title: '資深技術顧問',
    email: 'fan.bh@cxcrm.com',
    role: '技術顧問',
  },
  {
    av: '沈',
    g: 'rose',
    name: '沈宜蓁',
    title: '業務支援專員',
    email: 'shen.yz@cxcrm.com',
    role: '',
  },
  { av: '邱', g: 'blue', name: '邱柏睿', title: '儲備幹部', email: 'chiu.br@cxcrm.com', role: '' },
  {
    av: '顏',
    g: 'amber',
    name: '顏均豪',
    title: '技術支援工程師',
    email: 'yen.jh@cxcrm.com',
    role: '',
  },
  {
    av: '趙',
    g: 'cyan',
    name: '趙文心',
    title: '客戶成功專員',
    email: 'chao.wx@cxcrm.com',
    role: '',
  },
];

// ── Flow 資料 ─────────────────────────────────────────────────────────────────
export const FLOW_TRIGGER: Record<FlowTrig, { lbl: string; tag: string; kind: string }> = {
  record: { lbl: '記錄觸發', tag: '記錄觸發', kind: '記錄觸發 · 啟動' },
  schedule: { lbl: '排程', tag: '排程', kind: '排程 · 啟動' },
  screen: { lbl: '畫面流程', tag: '畫面流程', kind: '畫面流程 · 啟動' },
};
export const FLOWS: FlowItem[] = [
  {
    name: '商機結案自動建立續約',
    api: 'Opportunity_Won_Renewal',
    trig: 'record',
    obj: '商機 Opportunity',
    desc: '當商機階段變更為「結案 — 贏單」且含保固類產品時，自動建立續約商機並通知負責業務。',
    on: true,
    ver: 4,
    runs7: 842,
    fail7: 0,
    lm: { av: '王', g: 'navy', name: '王淑芬', date: '2026/06/12' },
    diagram: [
      { start: true, trig: 'record', label: '商機 Opportunity', sub: '階段變更為 結案-贏單 時' },
      { ic: 'get', label: '取得商機產品明細', sub: 'OpportunityLineItem' },
      {
        decision: true,
        label: '含保固類產品？',
        sub: 'Product.Family = Warranty',
        yes: [
          { ic: 'create', label: '建立續約商機', sub: '到期前 90 天' },
          { ic: 'action', label: '通知負責業務', sub: 'Email + 站內通知' },
        ],
        no: [{ end: true, label: '結束 — 不處理' }],
      },
    ],
  },
  {
    name: '高額折扣自動送審',
    api: 'Quote_Discount_Approval',
    trig: 'record',
    obj: '報價單 Quote',
    desc: '報價單建立或編輯時，比對提交者角色折扣上限，超限自動送出審核給上層主管。',
    on: true,
    ver: 7,
    runs7: 1310,
    fail7: 6,
    lm: { av: '陳', g: 'green', name: '陳小明', date: '2026/06/15' },
    diagram: [
      { start: true, trig: 'record', label: '報價單 Quote', sub: '建立或更新時' },
      { ic: 'get', label: '取得提交者角色上限', sub: 'Role.DiscountCap__c' },
      {
        decision: true,
        label: '折扣 > 角色上限？',
        yes: [
          { ic: 'action', label: '送出審核給上層主管', sub: 'Approval Process' },
          { ic: 'update', label: '標記狀態 = 審核中' },
        ],
        no: [
          { ic: 'update', label: '標記狀態 = 已核准' },
          { end: true, label: '自動核准' },
        ],
      },
    ],
  },
  {
    name: '新名單自動指派業務',
    api: 'Lead_Auto_Assignment',
    trig: 'record',
    obj: '名單 Lead',
    desc: '名單建立時依來源與地區，套用指派規則分派給對應業務團隊並記錄指派時間。',
    on: true,
    ver: 2,
    runs7: 476,
    fail7: 0,
    lm: { av: '林', g: 'violet', name: '林雅婷', date: '2026/05/28' },
    diagram: [
      { start: true, trig: 'record', label: '名單 Lead', sub: '建立時' },
      { ic: 'get', label: '取得地區業務團隊', sub: '依 Lead.Region__c' },
      {
        decision: true,
        label: '名單來源 = 官網？',
        yes: [{ ic: 'assign', label: '指派給內勤業務', sub: 'Inbound 隊列' }],
        no: [{ ic: 'assign', label: '指派給區域外勤業務' }],
      },
      { ic: 'update', label: '記錄指派時間', sub: 'AssignedAt__c = NOW()' },
    ],
  },
  {
    name: '每日逾期商機提醒',
    api: 'Daily_Stale_Opp_Reminder',
    trig: 'schedule',
    obj: '排程 · 每日 08:00',
    desc: '每日早晨掃描逾 14 天未更新的進行中商機，彙整摘要寄送給負責業務與其主管。',
    on: true,
    ver: 3,
    runs7: 7,
    fail7: 0,
    lm: { av: '王', g: 'navy', name: '王淑芬', date: '2026/06/01' },
    diagram: [
      { start: true, trig: 'schedule', label: '每日 08:00', sub: 'Scheduled Flow' },
      { ic: 'get', label: '取得逾期商機', sub: '14 天未更新 · 進行中' },
      {
        decision: true,
        label: '有逾期商機？',
        yes: [{ ic: 'action', label: '寄送摘要 Email', sub: '分組寄給各負責業務' }],
        no: [{ end: true, label: '結束 — 無待辦' }],
      },
    ],
  },
  {
    name: '報價單產生畫面流程',
    api: 'Quote_Builder_Screen',
    trig: 'screen',
    obj: '畫面流程 · 使用者啟動',
    desc: '引導業務逐步選擇產品、套用價目表與折扣規則，並在確認後建立報價單。',
    on: true,
    ver: 5,
    runs7: 318,
    fail7: 1,
    lm: { av: '陳', g: 'green', name: '陳小明', date: '2026/06/10' },
    diagram: [
      { start: true, trig: 'screen', label: '使用者啟動', sub: '商機頁面按鈕' },
      { ic: 'screen', label: '選擇產品與數量' },
      { ic: 'get', label: '取得價目表與折扣規則' },
      { ic: 'screen', label: '確認報價明細' },
      { ic: 'create', label: '建立報價單', sub: 'Quote + QuoteLineItem' },
      { end: true, label: '完成' },
    ],
  },
  {
    name: 'Cisco 保固到期通知',
    api: 'Cisco_Warranty_Expiry',
    trig: 'schedule',
    obj: '排程 · 每日 07:00',
    desc: '每日呼叫 Cisco API 同步保固狀態，對 90 天內到期者建立續約行動項目並通知客戶經理。',
    on: true,
    ver: 1,
    runs7: 7,
    fail7: 5,
    lm: { av: '王', g: 'navy', name: '王淑芬', date: '2026/06/16' },
    diagram: [
      { start: true, trig: 'schedule', label: '每日 07:00', sub: 'Scheduled Flow' },
      { ic: 'action', label: '呼叫 Cisco 保固 API', sub: 'External Service' },
      {
        decision: true,
        label: '90 天內到期？',
        yes: [
          { ic: 'create', label: '建立續約行動項目', sub: 'CallToAction__c' },
          { ic: 'action', label: '通知客戶經理' },
        ],
        no: [{ end: true, label: '結束' }],
      },
    ],
  },
  {
    name: '客戶滿意度調查',
    api: 'CSAT_Survey_OnClose',
    trig: 'screen',
    obj: '服務案件 Case',
    desc: '服務案件結案後彈出滿意度問卷，並將評分寫回案件。目前為草稿，尚未啟用。',
    on: false,
    ver: 1,
    runs7: 0,
    fail7: 0,
    lm: { av: '林', g: 'violet', name: '林雅婷', date: '2026/06/14' },
    diagram: [
      { start: true, trig: 'screen', label: '案件結案後', sub: '草稿 Draft' },
      { ic: 'screen', label: '滿意度問卷', sub: 'CSAT 1–5 分' },
      { ic: 'update', label: '寫回案件評分', sub: 'Case.CSAT__c' },
      { end: true, label: '完成' },
    ],
  },
];
export const FLOW_RUNS: Record<number | 'default', RunEntry[]> = {
  default: [
    {
      ok: 1,
      t: '執行成功',
      d: '處理 1 筆記錄，2 個元素已執行。',
      time: '今天 14:22',
      dur: '0.42s',
    },
    {
      ok: 1,
      t: '執行成功',
      d: '處理 1 筆記錄，2 個元素已執行。',
      time: '今天 11:08',
      dur: '0.39s',
    },
    { ok: 1, t: '執行成功', d: '處理 1 筆記錄。', time: '今天 09:51', dur: '0.51s' },
    { ok: 1, t: '執行成功', d: '處理 1 筆記錄。', time: '昨天 17:30', dur: '0.44s' },
  ],
  1: [
    {
      ok: 0,
      t: '執行失敗',
      d: '動作「送出審核」失敗：找不到提交者的上層主管（Manager 欄位為空）。',
      time: '今天 13:15',
      dur: '0.88s',
    },
    {
      ok: 1,
      t: '執行成功',
      d: '折扣 22% 超限，已送審核給 王淑芬。',
      time: '今天 12:40',
      dur: '0.55s',
    },
    {
      ok: 0,
      t: '執行失敗',
      d: '動作「送出審核」失敗：找不到提交者的上層主管（Manager 欄位為空）。',
      time: '今天 10:02',
      dur: '0.91s',
    },
    { ok: 1, t: '執行成功', d: '折扣 8%，未超限，自動核准。', time: '今天 09:18', dur: '0.33s' },
  ],
  5: [
    {
      ok: 0,
      t: '執行失敗',
      d: '呼叫 Cisco 保固 API 逾時（10s）— External Service「CiscoWarranty」未回應。',
      time: '今天 07:00',
      dur: '10.0s',
    },
    {
      ok: 0,
      t: '執行失敗',
      d: '呼叫 Cisco 保固 API 逾時（10s）。',
      time: '昨天 07:00',
      dur: '10.0s',
    },
    {
      ok: 0,
      t: '執行失敗',
      d: 'HTTP 401 — API 金鑰已過期，請至「系統整合 › API 設定」更新。',
      time: '06/15 07:00',
      dur: '1.2s',
    },
    { ok: 0, t: '執行失敗', d: 'HTTP 401 — API 金鑰已過期。', time: '06/14 07:00', dur: '1.1s' },
  ],
};
export const FLOW_VERSIONS: Record<number | 'default', VerEntry[]> = {
  default: [
    {
      v: '目前版本',
      active: true,
      date: '2026/06/12',
      by: '王淑芬',
      note: '調整通知收件人，新增主管副本。',
    },
    { v: 'v3', active: false, date: '2026/04/30', by: '王淑芬', note: '加入保固產品判斷條件。' },
    { v: 'v2', active: false, date: '2026/02/18', by: '陳小明', note: '初版上線。' },
  ],
  1: [
    {
      v: '目前版本',
      active: true,
      date: '2026/06/15',
      by: '陳小明',
      note: '依角色折扣上限改寫判斷，串接審核流程。',
    },
    { v: 'v6', active: false, date: '2026/05/20', by: '陳小明', note: '新增「已核准」狀態回寫。' },
    { v: 'v5', active: false, date: '2026/03/11', by: '王淑芬', note: '調整審核路由規則。' },
  ],
  5: [
    {
      v: '目前版本',
      active: true,
      date: '2026/06/16',
      by: '王淑芬',
      note: '串接 Cisco 保固 API（External Service）。',
    },
  ],
};

// ── Import Batch 資料 ─────────────────────────────────────────────────────────
export const IMP_SOURCE: Record<ImpSrc, { tag: string }> = {
  csv: { tag: 'CSV 上傳' },
  api: { tag: 'API 同步' },
  manual: { tag: '手動上傳' },
};
export const IMP_STATUS: Record<ImpStatus, { cls: string; lbl: string }> = {
  scheduled: { cls: 'active', lbl: '排程中' },
  processing: { cls: 'proc', lbl: '處理中' },
  completed: { cls: 'active', lbl: '完成' },
  partial: { cls: 'pending', lbl: '部分失敗' },
  failed: { cls: 'inactive', lbl: '失敗' },
  queued: { cls: 'queue', lbl: '排隊中' },
};
export const IMP_RULES = [
  { l: '重複比對欄位', v: 'Email · 統一編號' },
  { l: '重複處理方式', v: '更新既有紀錄（Upsert）' },
  { l: '批次大小', v: '每批 200 筆' },
  { l: '錯誤門檻', v: '失敗 > 10% 自動中止' },
  { l: '預設負責人', v: '依指派規則 / 上傳者' },
  { l: '完成通知', v: 'Email 通知上傳者與管理員' },
];
export const BATCHES: BatchItem[] = [
  {
    name: '每日潛客匯入',
    file: 'leads_daily.csv',
    obj: '名單 Lead',
    src: 'api',
    freq: '排程 · 每日 02:00',
    status: 'scheduled',
    sched: true,
    on: true,
    total: 128,
    ok: 128,
    err: 0,
    skip: 4,
    by: { av: '系', g: 'navy', name: '系統排程', date: '今天 02:00' },
    dur: '14s',
  },
  {
    name: 'ERP 客戶同步',
    file: 'SAP OData',
    obj: '客戶帳號 Account',
    src: 'api',
    freq: '排程 · 每 6 小時',
    status: 'scheduled',
    sched: true,
    on: true,
    total: 42,
    ok: 42,
    err: 0,
    skip: 8,
    by: { av: '系', g: 'navy', name: '系統排程', date: '今天 06:00' },
    dur: '9s',
  },
  {
    name: 'Cisco 保固清單匯入',
    file: 'cisco_warranty_q2.csv',
    obj: '保固續約 Cisco_Warranty_Renewal__c',
    src: 'manual',
    freq: '一次性',
    status: 'processing',
    sched: false,
    on: false,
    total: 1240,
    ok: 794,
    err: 6,
    skip: 0,
    prog: 64,
    by: { av: '王', g: 'navy', name: '王淑芬', date: '今天 14:38' },
    dur: '進行中',
  },
  {
    name: '行銷名單匯入（展會）',
    file: 'expo2026_leads.xlsx',
    obj: '名單 Lead',
    src: 'manual',
    freq: '一次性',
    status: 'completed',
    sched: false,
    on: false,
    total: 560,
    ok: 548,
    err: 0,
    skip: 12,
    by: { av: '林', g: 'violet', name: '林雅婷', date: '昨天 16:20' },
    dur: '31s',
  },
  {
    name: '歷史商機匯入',
    file: 'opps_2024_archive.csv',
    obj: '商機 Opportunity',
    src: 'csv',
    freq: '一次性',
    status: 'partial',
    sched: false,
    on: false,
    total: 312,
    ok: 309,
    err: 3,
    skip: 0,
    by: { av: '陳', g: 'green', name: '陳小明', date: '06/16 11:02' },
    dur: '22s',
  },
  {
    name: '聯絡人批次更新',
    file: 'contacts_update.csv',
    obj: '聯絡人 Contact',
    src: 'csv',
    freq: '一次性',
    status: 'failed',
    sched: false,
    on: false,
    total: 0,
    ok: 0,
    err: 0,
    skip: 0,
    by: { av: '林', g: 'violet', name: '林雅婷', date: '06/16 09:45' },
    dur: '—',
    failReason: '檔案編碼非 UTF-8，且第 1 列標頭與欄位對應不符，匯入未啟動。',
  },
  {
    name: '產品價目表匯入',
    file: 'pricebook_2026h2.csv',
    obj: '產品 Product2',
    src: 'csv',
    freq: '一次性',
    status: 'queued',
    sched: false,
    on: false,
    total: 86,
    ok: 0,
    err: 0,
    skip: 0,
    by: { av: '王', g: 'navy', name: '王淑芬', date: '今天 14:51' },
    dur: '排隊中',
  },
];
export const IMP_ERRORS: Record<number, ImpErrEntry[]> = {
  2: [
    { row: 118, id: 'CSCO-2291', reason: '保固到期日格式錯誤（應為 YYYY-MM-DD）。' },
    { row: 204, id: 'CSCO-2310', reason: '關聯帳號「鴻博科技」查無對應 Account。' },
    { row: 377, id: 'CSCO-2402', reason: 'Cisco 合約號重複，已存在相同紀錄。' },
  ],
  4: [
    { row: 57, id: 'OPP-2024-0571', reason: '金額欄位為空，必填欄位驗證失敗。' },
    { row: 142, id: 'OPP-2024-1183', reason: '階段「Closed」非有效選項清單值。' },
    { row: 288, id: 'OPP-2024-2240', reason: '負責業務 Email 查無對應使用者。' },
  ],
};
export const IMP_MAPPING: Record<number | 'default', MapRow[]> = {
  default: [
    ['name', '名稱', 'Name', 'ok'],
    ['email', 'Email', 'Email', 'ok'],
    ['company', '公司', 'Company', 'ok'],
    ['phone', '電話', 'Phone', 'ok'],
    ['source', '來源', 'LeadSource', 'ok'],
    ['notes', '—', '—', 'skip'],
  ],
  2: [
    ['contract_no', 'Cisco 合約號', 'Cisco_Contract_No__c', 'ok'],
    ['account', '關聯帳號', 'Account__c', 'ok'],
    ['warranty_end', '保固到期日', 'Warranty_End__c', 'ok'],
    ['amount', '續約金額', 'Renewal_Amount__c', 'ok'],
    ['status', '續約狀態', 'Renewal_Status__c', 'ok'],
    ['internal_id', '—', '—', 'skip'],
  ],
  4: [
    ['opp_name', '商機名稱', 'Name', 'ok'],
    ['amount', '金額', 'Amount', 'ok'],
    ['stage', '階段', 'StageName', 'ok'],
    ['close_date', '預計關閉日', 'CloseDate', 'ok'],
    ['owner_email', '負責業務', 'OwnerId', 'ok'],
    ['legacy_note', '—', '—', 'skip'],
  ],
};
export const IMP_RECORDS: Record<number | 'default', ImpRecEntry[]> = {
  default: [
    { id: 'LEAD-0042', name: '張庭瑋 / 宏立科技', status: 'ok' },
    { id: 'LEAD-0043', name: '李孟潔 / 優思資訊', status: 'ok' },
    {
      id: 'LEAD-0044',
      name: '王柏宇 / 鼎新電腦',
      status: 'skip',
      note: '重複 Email — 已 Upsert 更新',
    },
    { id: 'LEAD-0045', name: '陳怡安 / 凱基系統', status: 'ok' },
    { id: 'LEAD-0046', name: '林志豪 / 聯華電子', status: 'ok' },
  ],
  1: [
    { id: 'ACC-1201', name: '宏立科技股份有限公司', status: 'ok' },
    { id: 'ACC-1202', name: '優思資訊有限公司', status: 'ok' },
    { id: 'ACC-1203', name: '鼎新電腦股份有限公司', status: 'ok' },
  ],
  2: [
    { id: 'LEAD-0051', name: '劉怡婷 / 英業達', status: 'ok' },
    { id: 'LEAD-0052', name: '陳冠宏 / 仁寶電腦', status: 'err', note: '缺少必填欄位「公司」' },
    { id: 'LEAD-0053', name: '吳佩儀 / 廣達電腦', status: 'ok' },
    {
      id: 'LEAD-0054',
      name: '黃俊豪 / 和碩聯合',
      status: 'skip',
      note: '重複 Email — 已 Upsert 更新',
    },
    { id: 'LEAD-0055', name: '許雅涵 / 微星科技', status: 'ok' },
  ],
  4: [
    { id: 'OPP-0841', name: '宏立科技-ERP導入案', status: 'ok' },
    { id: 'OPP-0842', name: '優思資訊-雲端續約', status: 'ok' },
    {
      id: 'OPP-0843',
      name: '鼎新電腦-資安方案',
      status: 'err',
      note: '必填欄位「預計關閉日」格式錯誤',
    },
    { id: 'OPP-0844', name: '凱基系統-網路設備採購', status: 'ok' },
  ],
};

export const EMAIL_CATS: Record<string, EmailCategory> = {
  sales: { nm: '業務 / 商機', hex: '#3B82F6', v: 'blue' },
  cs: { nm: '客戶成功', hex: '#059669', v: 'green' },
  service: { nm: '服務支援', hex: '#0369a1', v: 'cyan' },
  mkt: { nm: '行銷活動', hex: '#be185d', v: 'pink' },
  sys: { nm: '系統通知', hex: '#6d28d9', v: 'violet' },
};

export const EMAIL_SENT_30D = '3,480';

export const SIG: EmailSig = {
  name: '{{User.Name}}',
  title: '{{User.Title}}｜CX CRM',
  phone: '{{User.Phone}}',
};

export const EMAIL_TEMPLATES_INIT: EmailTemplate[] = [
  {
    k: 'quote_send',
    name: '報價單寄送',
    cat: 'sales',
    icon: 'send',
    on: true,
    used: '2 天前',
    from: '業務負責人 <{{User.Email}}>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '您的報價單 {{Opportunity.Name}} 已備妥',
    body: [
      { kind: 'greet', text: '親愛的 {{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '感謝您對本公司方案的關注。針對 {{Account.Name}} 的需求，我們已為您備妥報價，明細如下：',
      },
      {
        kind: 'quote',
        rows: [
          ['方案', '{{Quote.Name}}'],
          ['有效期限', '{{Quote.ExpirationDate}}'],
        ],
        total: ['報價總額', '{{Quote.TotalAmount}}'],
      },
      {
        kind: 'p',
        text: '報價於上述期限內有效。如需調整方案內容或安排線上說明，歡迎隨時與我聯繫。',
      },
      { kind: 'cta', text: '檢視完整報價單' },
      { kind: 'sig', sig: SIG },
    ],
  },
  {
    k: 'proposal_followup',
    name: '提案後跟進',
    cat: 'sales',
    icon: 'chat',
    on: true,
    used: '5 天前',
    from: '業務負責人 <{{User.Email}}>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '關於 {{Opportunity.Name}} 提案的後續',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '很高興日前能向 {{Account.Name}} 團隊介紹我們的解決方案。想跟進了解貴司內部評估的進度，以及是否還有任何我能協助釐清的地方。',
      },
      {
        kind: 'p',
        text: '若方便的話，我們可安排一場 30 分鐘的線上會議，針對導入時程與投資報酬進一步討論。',
      },
      { kind: 'cta', text: '安排線上會議' },
      { kind: 'sig', sig: SIG },
    ],
  },
  {
    k: 'won_notify',
    name: '贏單恭賀通知',
    cat: 'sales',
    icon: 'trophy',
    on: true,
    used: '1 週前',
    from: 'CX CRM 團隊 <success@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '歡迎加入！感謝 {{Account.Name}} 選擇 CX CRM',
    body: [
      { kind: 'greet', text: '親愛的 {{Contact.FirstName}}，' },
      {
        kind: 'p',
        text: '恭喜！{{Account.Name}} 與 CX CRM 的合作正式啟動。您的專屬客戶成功經理將於一個工作天內與您聯繫，協助安排導入啟動會議。',
      },
      { kind: 'p', text: '我們非常期待與您一同推動業務數位化的下一步。' },
      { kind: 'cta', text: '查看導入指南' },
      {
        kind: 'sig',
        sig: {
          name: '{{Opportunity.Owner}}',
          title: '業務負責人｜CX CRM',
          phone: '{{User.Phone}}',
        },
      },
    ],
  },
  {
    k: 'onboarding_welcome',
    name: '導入歡迎信',
    cat: 'cs',
    icon: 'welcome',
    on: true,
    used: '3 天前',
    from: '客戶成功 <success@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '歡迎啟用 CX CRM，{{Contact.FirstName}}！',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，歡迎加入 CX CRM 🎉' },
      {
        kind: 'p',
        text: '您的帳號已開通。為了讓 {{Account.Name}} 團隊更快上手，我們準備了一份導入清單，協助您在第一週完成基本設定與資料匯入。',
      },
      { kind: 'p', text: '有任何問題，您的客戶成功經理 {{User.Name}} 隨時為您服務。' },
      { kind: 'cta', text: '開始導入設定' },
      { kind: 'sig', sig: SIG },
    ],
  },
  {
    k: 'renewal_reminder',
    name: '續約到期提醒',
    cat: 'cs',
    icon: 'refresh',
    on: true,
    used: '昨天',
    from: '客戶成功 <success@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '{{Account.Name}} 的服務將於 {{Contract.EndDate}} 到期',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '提醒您，{{Account.Name}} 目前的服務合約將於 {{Contract.EndDate}} 到期。為確保服務不中斷，建議於到期前完成續約確認。',
      },
      {
        kind: 'quote',
        rows: [
          ['合約方案', '{{Contract.Name}}'],
          ['到期日', '{{Contract.EndDate}}'],
        ],
        total: ['續約金額', '{{Contract.RenewalAmount}}'],
      },
      { kind: 'cta', text: '確認續約方案' },
      { kind: 'sig', sig: SIG },
    ],
  },
  {
    k: 'case_created',
    name: '案件已建立通知',
    cat: 'service',
    icon: 'ticket',
    on: true,
    used: '4 小時前',
    from: '客服中心 <support@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '您的服務案件 {{Case.Number}} 已建立',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '我們已收到您的請求，案件編號為 {{Case.Number}}。客服團隊將於服務時間內盡快與您聯繫，目前優先等級為 {{Case.Priority}}。',
      },
      { kind: 'p', text: '您可隨時透過下方連結追蹤處理進度。' },
      { kind: 'cta', text: '查看案件狀態' },
      {
        kind: 'sig',
        sig: {
          name: 'CX CRM 客服中心',
          title: '服務時間 週一至週五 09:00–18:00',
          phone: '0800-000-000',
        },
      },
    ],
  },
  {
    k: 'case_resolved',
    name: '案件已解決通知',
    cat: 'service',
    icon: 'checkc',
    on: true,
    used: '1 天前',
    from: '客服中心 <support@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '案件 {{Case.Number}} 已解決',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '您的案件 {{Case.Number}} 已處理完成並關閉。若問題仍未解決，您可在 7 天內回覆此通知重新開啟案件。',
      },
      { kind: 'p', text: '我們很重視您的回饋，誠摯邀請您給予本次服務評分。' },
      { kind: 'cta', text: '填寫滿意度調查' },
      {
        kind: 'sig',
        sig: { name: 'CX CRM 客服中心', title: '感謝您的耐心與配合', phone: '0800-000-000' },
      },
    ],
  },
  {
    k: 'event_invite',
    name: '活動邀請',
    cat: 'mkt',
    icon: 'calendar',
    on: true,
    used: '2 週前',
    from: '行銷團隊 <events@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '邀請您參加 {{Campaign.Name}}',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '誠摯邀請您參加 {{Campaign.Name}}。本次活動將分享產業最佳實務與產品最新藍圖，名額有限，敬請及早報名。',
      },
      {
        kind: 'quote',
        rows: [
          ['日期', '{{Campaign.StartDate}}'],
          ['地點', '{{Campaign.Location}}'],
        ],
        total: ['報名費用', '免費'],
      },
      { kind: 'cta', text: '立即報名' },
      {
        kind: 'sig',
        sig: { name: 'CX CRM 行銷團隊', title: '期待與您相見', phone: 'events@cxcrm.com' },
      },
    ],
  },
  {
    k: 'approval_notify',
    name: '審核待辦通知',
    cat: 'sys',
    icon: 'gavel',
    on: true,
    used: '30 分鐘前',
    from: 'CX CRM 系統 <no-reply@cxcrm.com>',
    to: '{{Approver.Email}}',
    lang: '繁體中文',
    subj: '待您審核：{{Quote.Name}}（折扣 {{Quote.Discount}}）',
    body: [
      { kind: 'greet', text: '{{Approver.Name}} 您好，' },
      {
        kind: 'p',
        text: '有一筆報價需要您的審核。由 {{User.Name}} 提交，因折扣 {{Quote.Discount}} 超過該角色上限，已自動送出至您的待審清單。',
      },
      {
        kind: 'quote',
        rows: [
          ['商機', '{{Opportunity.Name}}'],
          ['提交人', '{{User.Name}}'],
          ['折扣', '{{Quote.Discount}}'],
        ],
        total: ['報價金額', '{{Quote.TotalAmount}}'],
      },
      { kind: 'cta', text: '前往審核' },
      {
        kind: 'sig',
        sig: { name: 'CX CRM 系統通知', title: '此為自動發送，請勿直接回覆', phone: '' },
      },
    ],
  },
  {
    k: 'newsletter',
    name: '月度電子報',
    cat: 'mkt',
    icon: 'news',
    on: false,
    used: '1 個月前',
    from: '行銷團隊 <news@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: 'CX CRM 月報｜本月產品更新與客戶案例',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '這是本月的 CX CRM 月報，為您整理產品新功能、實用技巧與精選客戶成功案例。',
      },
      { kind: 'cta', text: '閱讀本期月報' },
      { kind: 'sig', sig: { name: 'CX CRM 行銷團隊', title: '每月一封，與您分享', phone: '' } },
    ],
  },
  {
    k: 'qbr_invite',
    name: 'QBR 季度回顧邀約',
    cat: 'cs',
    icon: 'calendar',
    on: false,
    used: '未使用',
    from: '客戶成功 <success@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '邀請 {{Account.Name}} 進行季度業務回顧（QBR）',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '又到了季度業務回顧的時間。想與 {{Account.Name}} 團隊一同檢視本季成效、使用狀況與下一季的目標規劃。',
      },
      { kind: 'cta', text: '預約 QBR 時段' },
      { kind: 'sig', sig: SIG },
    ],
  },
  {
    k: 'win_back',
    name: '沉睡客戶喚回',
    cat: 'cs',
    icon: 'back',
    on: false,
    used: '未使用',
    from: '客戶成功 <success@cxcrm.com>',
    to: '{{Contact.Email}}',
    lang: '繁體中文',
    subj: '我們想念您，{{Contact.FirstName}}',
    body: [
      { kind: 'greet', text: '{{Contact.FirstName}} 您好，' },
      {
        kind: 'p',
        text: '注意到 {{Account.Name}} 近期較少使用 CX CRM。若有任何使用上的困難或需求變化，我們很樂意協助，也準備了專屬方案歡迎您回來。',
      },
      { kind: 'cta', text: '與我們聊聊' },
      { kind: 'sig', sig: SIG },
    ],
  },
];

export const EMAIL_MERGE: EmailMergeGroup[] = [
  {
    g: '商機 Opportunity',
    f: [
      '{{Opportunity.Name}}',
      '{{Opportunity.Amount}}',
      '{{Opportunity.StageName}}',
      '{{Opportunity.CloseDate}}',
      '{{Opportunity.Owner}}',
    ],
  },
  { g: '客戶帳號 Account', f: ['{{Account.Name}}', '{{Account.Industry}}', '{{Account.Owner}}'] },
  {
    g: '聯絡人 Contact',
    f: ['{{Contact.FirstName}}', '{{Contact.LastName}}', '{{Contact.Email}}', '{{Contact.Title}}'],
  },
  {
    g: '報價單 Quote',
    f: [
      '{{Quote.Name}}',
      '{{Quote.TotalAmount}}',
      '{{Quote.ExpirationDate}}',
      '{{Quote.Discount}}',
    ],
  },
  { g: '使用者 User', f: ['{{User.Name}}', '{{User.Title}}', '{{User.Phone}}', '{{User.Email}}'] },
];

export const PL_OBJECTS = [
  '商機 Opportunity',
  '客戶帳號 Account',
  '報價單 Quote__c',
  '聯絡人 Contact',
];

export const PL_PILLS: Record<string, string[]> = {
  '商機 Opportunity': ['商機 — 業務版面', '商機 — 主管版面'],
  '客戶帳號 Account': ['客戶帳號 — 標準版面'],
  '報價單 Quote__c': ['報價單 — 審核版面'],
  '聯絡人 Contact': ['聯絡人 — 標準版面'],
};

export const PL_PALETTE: Record<PLPaletteTab, PLPaletteGroup[]> = {
  fields: [
    {
      g: '標準欄位',
      items: [
        { n: '競爭對手', t: '文字(80)' },
        { n: '下一步行動', t: '文字(120)' },
        { n: '損失原因', t: '選項清單' },
        { n: '付款條件', t: '選項清單' },
        { n: '折扣率', t: '百分比' },
        { n: '回報關係', t: '查詢' },
      ],
    },
    {
      g: '自訂欄位',
      items: [
        { n: '產業別', t: '選項清單', c: 'violet' },
        { n: '採購窗口', t: '查詢', c: 'violet' },
        { n: '合約編號', t: '文字(40)', c: 'violet' },
        { n: 'PoC 完成', t: '核取方塊', c: 'violet' },
      ],
    },
  ],
  buttons: [
    {
      g: '標準按鈕',
      items: [
        { n: '編輯', t: 'Standard', c: 'blue' },
        { n: '刪除', t: 'Standard', c: 'blue' },
        { n: '複製', t: 'Standard', c: 'blue' },
        { n: '變更負責人', t: 'Standard', c: 'blue' },
        { n: '送出審核', t: 'Standard', c: 'blue' },
      ],
    },
    {
      g: '自訂按鈕',
      items: [
        { n: '產生報價', t: 'Flow', c: 'green' },
        { n: '同步至 ERP', t: 'Apex', c: 'orange' },
        { n: '排程 QBR', t: 'URL', c: 'cyan' },
      ],
    },
  ],
  related: [
    {
      g: '可用相關清單',
      items: [
        { n: '聯絡角色', t: 'OpportunityContactRole', c: 'cyan' },
        { n: '產品明細', t: 'OpportunityLineItem', c: 'green' },
        { n: '報價單', t: 'Quote', c: 'orange' },
        { n: '活動', t: 'ActivityHistory', c: 'violet' },
        { n: '附件', t: 'ContentDocument', c: 'blue' },
        { n: '核准歷程', t: 'ProcessInstance', c: 'pink' },
      ],
    },
  ],
};

export const PL_SECTIONS_INIT: PLSection[] = [
  {
    t: '重點資訊',
    cols: 2,
    fields: [
      { n: '商機名稱', t: '文字(120)', req: true },
      { n: '客戶帳號', t: '查詢 · Account', req: true },
      { n: '金額', t: '貨幣' },
      { n: '階段', t: '選項清單', req: true },
      { n: '預計成交日', t: '日期' },
      { n: '成交機率', t: '百分比' },
    ],
  },
  {
    t: '詳細資訊',
    cols: 2,
    fields: [
      { n: '負責業務', t: '查詢 · User' },
      { n: '商機來源', t: '選項清單' },
      { n: '產品線', t: '選項清單' },
      { n: '預算狀態', t: '選項清單' },
      { n: '描述', t: '長文字', full: true },
      { empty: true },
    ],
  },
  {
    t: '系統資訊',
    cols: 2,
    collapsed: true,
    fields: [
      { n: '建立者', t: '唯讀' },
      { n: '建立日期', t: '唯讀' },
      { n: '最後修改者', t: '唯讀' },
      { n: '最後修改日期', t: '唯讀' },
    ],
  },
];

export const PL_REL: PLRelCard[] = [
  { n: '聯絡角色', s: '3 筆', c: 'cyan' },
  { n: '產品明細', s: '5 筆', c: 'green' },
  { n: '報價單', s: '2 筆', c: 'orange' },
  { n: '活動', s: '8 筆', c: 'violet' },
];

export const PL_ASSIGNED = 6;
export const PL_UNASSIGNED = 1;

// Profile 管理面板與 DetailDrawer（ProfileContent）共用的假資料。
export const PROFILES: ProfileData[] = [
  {
    name: '系統管理員',
    users: 2,
    license: 'Salesforce',
    lic: 'sf',
    access: 'full',
    sys: ['管理使用者', '修改所有資料', '檢視設定與組態', '管理 Permission Set'],
    desc: '完整系統存取與設定權限，僅供 IT 與系統管理人員使用。',
  },
  {
    name: '業務經理',
    users: 3,
    license: 'Salesforce',
    lic: 'sf',
    access: 'rw',
    sys: ['檢視團隊所有商機', '匯出報表', '管理預測', '轉移擁有權'],
    desc: '可讀寫團隊資料、檢視報表與業績預測，管理下屬商機。',
  },
  {
    name: '標準業務',
    users: 8,
    license: 'Salesforce',
    lic: 'sf',
    access: 'std',
    sys: ['建立與編輯自有紀錄', '記錄活動', '使用清單檢視'],
    desc: '業務代表預設 Profile，可讀寫自有客戶與商機。',
  },
  {
    name: '業務支援',
    users: 4,
    license: 'Salesforce',
    lic: 'sf',
    access: 'support',
    sys: ['存取知識庫', '記錄個案活動', '檢視帳號'],
    desc: '內勤支援角色，以個案、活動與知識庫為主。',
  },
  {
    name: '唯讀稽核',
    users: 2,
    license: 'Salesforce Platform',
    lic: 'platform',
    access: 'ro',
    sys: ['檢視所有資料', '匯出報表'],
    desc: '全物件唯讀，供稽核與財務查核使用，無寫入權限。',
  },
];

// Permission Set 指派面板與 DetailDrawer（PermSetContent）共用的假資料。
export const PERMSETS: PermSetData[] = [
  {
    name: '報表匯出',
    type: 'func',
    typeL: '功能',
    users: 12,
    desc: '允許將報表與清單檢視匯出為 CSV / Excel。',
    perms: [
      ['匯出報表', '將報表結果下載為檔案', true],
      ['匯出清單檢視', '下載清單檢視資料', true],
      ['排程報表寄送', '定期以 Email 寄送報表', false],
    ],
  },
  {
    name: '商機刪除',
    type: 'obj',
    typeL: '物件',
    users: 4,
    desc: '授予商機物件的刪除權限（預設 Profile 不含）。',
    perms: [
      ['刪除商機', '刪除自有與團隊商機', true],
      ['大量刪除', '於清單檢視批次刪除', false],
    ],
  },
  {
    name: 'API 存取',
    type: 'sys',
    typeL: '系統',
    users: 3,
    desc: '啟用 REST / Bulk API 與已連接的應用程式。',
    perms: [
      ['API 已啟用', '透過 REST / SOAP 存取資料', true],
      ['Bulk API', '大量資料批次處理', true],
      ['管理已連接應用程式', 'OAuth 連線管理', false],
    ],
  },
  {
    name: '大量匯入精靈',
    type: 'data',
    typeL: '資料',
    users: 5,
    desc: '使用資料匯入精靈批次建立 / 更新紀錄。',
    perms: [
      ['匯入個人紀錄', '匯入自有物件資料', true],
      ['匯入所有資料', '跨擁有者匯入', false],
    ],
  },
  {
    name: 'Cisco 整合',
    type: 'intg',
    typeL: '整合',
    users: 2,
    desc: '存取 Cisco Webex / CUCM 通話紀錄同步與點擊撥號。',
    perms: [
      ['通話紀錄同步', '自 CUCM 同步通話歷程', true],
      ['點擊撥號 (Click-to-Dial)', '於紀錄頁一鍵撥號', true],
      ['Webex 會議建立', '於商機建立 Webex 會議', true],
    ],
  },
  {
    name: '行銷活動管理',
    type: 'func',
    typeL: '功能',
    users: 6,
    desc: '建立與管理行銷活動及其成員名單。',
    perms: [
      ['管理行銷活動', '建立 / 編輯行銷活動', true],
      ['新增行銷活動成員', '加入聯絡人 / 潛客', true],
    ],
  },
];

// 各 Permission Set 已指派的使用者索引（對應 USERS）。
export const PERM_ASSIGNED: Record<string, number[]> = {
  報表匯出: [0, 1, 2, 3, 4],
  商機刪除: [0, 1],
  'API 存取': [1, 2],
  大量匯入精靈: [1, 3],
  'Cisco 整合': [1, 6],
  行銷活動管理: [2, 3],
};
