import type {
  RoleKey,
  UserData,
  RoleNode,
  RPerson,
  FlowTrig,
  FlowItem,
  RunEntry,
  VerEntry,
  ImpSrc,
  ImpStatus,
  BatchItem,
  ImpErrEntry,
  MapRow,
  ImpRecEntry,
} from './settings.types';

// 頭像漸層底色（依 g 色鍵）。
export const GRAD: Record<string, string> = {
  green: 'linear-gradient(135deg,#34D399,#10b981)',
  blue: 'linear-gradient(135deg,#60a5fa,#2563eb)',
  violet: 'linear-gradient(135deg,#a78bfa,#7c3aed)',
  amber: 'linear-gradient(135deg,#fbbf24,#f59e0b)',
  navy: 'linear-gradient(135deg,#3b82f6,#1e3a5f)',
  cyan: 'linear-gradient(135deg,#22d3ee,#0891b2)',
  rose: 'linear-gradient(135deg,#f87171,#dc2626)',
  teal: 'linear-gradient(135deg,#2dd4bf,#0d9488)',
};

export const ROLES: Record<RoleKey, { name: string; color: string; cap: number; over: string }> = {
  admin: { name: '系統管理員', color: '#2563eb', cap: 100, over: 'unlimited' },
  director: { name: '區域總監', color: '#6d28d9', cap: 40, over: 'approve' },
  manager: { name: '業務經理', color: '#0891b2', cap: 25, over: 'approve' },
  senior: { name: '資深業務', color: '#059669', cap: 15, over: 'approve' },
  rep: { name: '業務代表', color: '#ea7a1e', cap: 10, over: 'approve' },
  support: { name: '業務支援', color: '#9aa1ae', cap: 0, over: 'block' },
};

export const USERS: UserData[] = [
  {
    av: '陳',
    g: 'green',
    name: '陳小明',
    email: 'chen.xm@cxcrm.com',
    title: '資深業務經理',
    role: 'manager',
    profile: '業務經理',
    perms: ['報表匯出', '商機刪除'],
    status: 'active',
    last: '2 小時前',
    since: '2023/11/04',
  },
  {
    av: '王',
    g: 'navy',
    name: '王淑芬',
    email: 'wang.sf@cxcrm.com',
    title: 'IT 系統管理員',
    role: 'admin',
    profile: '系統管理員',
    perms: ['報表匯出', '商機刪除', 'API 存取', '大量匯入精靈', 'Cisco 整合'],
    status: 'active',
    last: '剛剛',
    since: '2022/08/15',
  },
  {
    av: '李',
    g: 'cyan',
    name: '李孟翰',
    email: 'lee.mh@cxcrm.com',
    title: '北區區域總監',
    role: 'director',
    profile: '業務經理',
    perms: ['報表匯出', 'API 存取'],
    status: 'active',
    last: '1 天前',
    since: '2023/02/20',
  },
  {
    av: '陳',
    g: 'violet',
    name: '陳美華',
    email: 'chen.mh@cxcrm.com',
    title: '資深業務',
    role: 'senior',
    profile: '標準業務',
    perms: ['報表匯出', '大量匯入精靈'],
    status: 'active',
    last: '3 小時前',
    since: '2023/06/11',
  },
  {
    av: '張',
    g: 'blue',
    name: '張志豪',
    email: 'chang.zh@cxcrm.com',
    title: '業務代表',
    role: 'rep',
    profile: '標準業務',
    perms: ['報表匯出'],
    status: 'active',
    last: '昨天',
    since: '2024/03/01',
  },
  {
    av: '林',
    g: 'amber',
    name: '林俊傑',
    email: 'lin.cj@cxcrm.com',
    title: '業務代表',
    role: 'rep',
    profile: '標準業務',
    perms: [],
    status: 'active',
    last: '5 天前',
    since: '2024/09/18',
  },
  {
    av: '吳',
    g: 'teal',
    name: '吳建宏',
    email: 'wu.jh@cxcrm.com',
    title: '資深業務',
    role: 'senior',
    profile: '標準業務',
    perms: ['Cisco 整合'],
    status: 'pending',
    last: '—',
    since: '2026/06/14',
  },
  {
    av: '黃',
    g: 'rose',
    name: '黃詩涵',
    email: 'huang.sh@cxcrm.com',
    title: '業務支援專員',
    role: 'support',
    profile: '業務支援',
    perms: [],
    status: 'inactive',
    last: '30 天前',
    since: '2023/01/09',
  },
];

// ── Roles 資料 ────────────────────────────────────────────────────────────────
export const ORG_NAME = 'CX CRM 股份有限公司';

export const ROLE_HIER: RoleNode[] = [
  { name: '客戶成功經理', code: 'CSM', color: '#0891b2' },
  { name: '續約經理', code: 'Renewal_Mgr', color: '#7c3aed' },
  { name: '產品經理', code: 'Product_Mgr', color: '#db2777' },
  {
    name: '業務主管',
    code: 'Sales_Lead',
    color: '#2563eb',
    children: [
      {
        name: '業務組長',
        code: 'Sales_TeamLead',
        color: '#0d9488',
        children: [{ name: '業務人員', code: 'Sales_Staff', color: '#059669' }],
      },
    ],
  },
  { name: '業務代表', code: 'Sales_Rep', color: '#ea7a1e' },
  { name: '技術顧問', code: 'Tech_Consult', color: '#6d28d9' },
];

export const RPEOPLE_INIT: RPerson[] = [
  {
    av: '林',
    g: 'rose',
    name: '林雅婷',
    title: '客戶成功資深專員',
    email: 'lin.yt@cxcrm.com',
    role: '客戶成功經理',
  },
  {
    av: '周',
    g: 'blue',
    name: '周冠宇',
    title: '客戶成功經理',
    email: 'chou.gy@cxcrm.com',
    role: '客戶成功經理',
  },
  {
    av: '蔡',
    g: 'violet',
    name: '蔡岱穎',
    title: '續約業務經理',
    email: 'tsai.dy@cxcrm.com',
    role: '續約經理',
  },
  {
    av: '鄭',
    g: 'cyan',
    name: '鄭凱文',
    title: '產品線經理',
    email: 'cheng.kw@cxcrm.com',
    role: '產品經理',
  },
  {
    av: '高',
    g: 'amber',
    name: '高敏華',
    title: '產品企劃經理',
    email: 'kao.mh@cxcrm.com',
    role: '產品經理',
  },
  {
    av: '李',
    g: 'navy',
    name: '李孟翰',
    title: '北區業務主管',
    email: 'lee.mh@cxcrm.com',
    role: '業務主管',
  },
  {
    av: '陳',
    g: 'green',
    name: '陳小明',
    title: '業務一組組長',
    email: 'chen.xm@cxcrm.com',
    role: '業務組長',
  },
  {
    av: '吳',
    g: 'teal',
    name: '吳建宏',
    title: '業務二組組長',
    email: 'wu.jh@cxcrm.com',
    role: '業務組長',
  },
  {
    av: '張',
    g: 'blue',
    name: '張志豪',
    title: '業務專員',
    email: 'chang.zh@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '林',
    g: 'amber',
    name: '林俊傑',
    title: '業務專員',
    email: 'lin.cj@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '黃',
    g: 'rose',
    name: '黃詩涵',
    title: '業務專員',
    email: 'huang.sh@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '許',
    g: 'cyan',
    name: '許文彥',
    title: '業務專員',
    email: 'hsu.wy@cxcrm.com',
    role: '業務人員',
  },
  {
    av: '劉',
    g: 'violet',
    name: '劉哲瑋',
    title: '業務代表',
    email: 'liu.zw@cxcrm.com',
    role: '業務代表',
  },
  {
    av: '楊',
    g: 'teal',
    name: '楊雅筑',
    title: '業務代表',
    email: 'yang.yz@cxcrm.com',
    role: '業務代表',
  },
  {
    av: '簡',
    g: 'green',
    name: '簡上瑋',
    title: '業務代表',
    email: 'chien.sw@cxcrm.com',
    role: '業務代表',
  },
  {
    av: '范',
    g: 'navy',
    name: '范柏宏',
    title: '資深技術顧問',
    email: 'fan.bh@cxcrm.com',
    role: '技術顧問',
  },
  {
    av: '沈',
    g: 'rose',
    name: '沈宜蓁',
    title: '業務支援專員',
    email: 'shen.yz@cxcrm.com',
    role: '',
  },
  { av: '邱', g: 'blue', name: '邱柏睿', title: '儲備幹部', email: 'chiu.br@cxcrm.com', role: '' },
  {
    av: '顏',
    g: 'amber',
    name: '顏均豪',
    title: '技術支援工程師',
    email: 'yen.jh@cxcrm.com',
    role: '',
  },
  {
    av: '趙',
    g: 'cyan',
    name: '趙文心',
    title: '客戶成功專員',
    email: 'chao.wx@cxcrm.com',
    role: '',
  },
];

// ── Flow 資料 ─────────────────────────────────────────────────────────────────
export const FLOW_TRIGGER: Record<FlowTrig, { lbl: string; tag: string; kind: string }> = {
  record: { lbl: '記錄觸發', tag: '記錄觸發', kind: '記錄觸發 · 啟動' },
  schedule: { lbl: '排程', tag: '排程', kind: '排程 · 啟動' },
  screen: { lbl: '畫面流程', tag: '畫面流程', kind: '畫面流程 · 啟動' },
};
export const FLOWS: FlowItem[] = [
  {
    name: '商機結案自動建立續約',
    api: 'Opportunity_Won_Renewal',
    trig: 'record',
    obj: '商機 Opportunity',
    desc: '當商機階段變更為「結案 — 贏單」且含保固類產品時，自動建立續約商機並通知負責業務。',
    on: true,
    ver: 4,
    runs7: 842,
    fail7: 0,
    lm: { av: '王', g: 'navy', name: '王淑芬', date: '2026/06/12' },
    diagram: [
      { start: true, trig: 'record', label: '商機 Opportunity', sub: '階段變更為 結案-贏單 時' },
      { ic: 'get', label: '取得商機產品明細', sub: 'OpportunityLineItem' },
      {
        decision: true,
        label: '含保固類產品？',
        sub: 'Product.Family = Warranty',
        yes: [
          { ic: 'create', label: '建立續約商機', sub: '到期前 90 天' },
          { ic: 'action', label: '通知負責業務', sub: 'Email + 站內通知' },
        ],
        no: [{ end: true, label: '結束 — 不處理' }],
      },
    ],
  },
  {
    name: '高額折扣自動送審',
    api: 'Quote_Discount_Approval',
    trig: 'record',
    obj: '報價單 Quote',
    desc: '報價單建立或編輯時，比對提交者角色折扣上限，超限自動送出審核給上層主管。',
    on: true,
    ver: 7,
    runs7: 1310,
    fail7: 6,
    lm: { av: '陳', g: 'green', name: '陳小明', date: '2026/06/15' },
    diagram: [
      { start: true, trig: 'record', label: '報價單 Quote', sub: '建立或更新時' },
      { ic: 'get', label: '取得提交者角色上限', sub: 'Role.DiscountCap__c' },
      {
        decision: true,
        label: '折扣 > 角色上限？',
        yes: [
          { ic: 'action', label: '送出審核給上層主管', sub: 'Approval Process' },
          { ic: 'update', label: '標記狀態 = 審核中' },
        ],
        no: [
          { ic: 'update', label: '標記狀態 = 已核准' },
          { end: true, label: '自動核准' },
        ],
      },
    ],
  },
  {
    name: '新名單自動指派業務',
    api: 'Lead_Auto_Assignment',
    trig: 'record',
    obj: '名單 Lead',
    desc: '名單建立時依來源與地區，套用指派規則分派給對應業務團隊並記錄指派時間。',
    on: true,
    ver: 2,
    runs7: 476,
    fail7: 0,
    lm: { av: '林', g: 'violet', name: '林雅婷', date: '2026/05/28' },
    diagram: [
      { start: true, trig: 'record', label: '名單 Lead', sub: '建立時' },
      { ic: 'get', label: '取得地區業務團隊', sub: '依 Lead.Region__c' },
      {
        decision: true,
        label: '名單來源 = 官網？',
        yes: [{ ic: 'assign', label: '指派給內勤業務', sub: 'Inbound 隊列' }],
        no: [{ ic: 'assign', label: '指派給區域外勤業務' }],
      },
      { ic: 'update', label: '記錄指派時間', sub: 'AssignedAt__c = NOW()' },
    ],
  },
  {
    name: '每日逾期商機提醒',
    api: 'Daily_Stale_Opp_Reminder',
    trig: 'schedule',
    obj: '排程 · 每日 08:00',
    desc: '每日早晨掃描逾 14 天未更新的進行中商機，彙整摘要寄送給負責業務與其主管。',
    on: true,
    ver: 3,
    runs7: 7,
    fail7: 0,
    lm: { av: '王', g: 'navy', name: '王淑芬', date: '2026/06/01' },
    diagram: [
      { start: true, trig: 'schedule', label: '每日 08:00', sub: 'Scheduled Flow' },
      { ic: 'get', label: '取得逾期商機', sub: '14 天未更新 · 進行中' },
      {
        decision: true,
        label: '有逾期商機？',
        yes: [{ ic: 'action', label: '寄送摘要 Email', sub: '分組寄給各負責業務' }],
        no: [{ end: true, label: '結束 — 無待辦' }],
      },
    ],
  },
  {
    name: '報價單產生畫面流程',
    api: 'Quote_Builder_Screen',
    trig: 'screen',
    obj: '畫面流程 · 使用者啟動',
    desc: '引導業務逐步選擇產品、套用價目表與折扣規則，並在確認後建立報價單。',
    on: true,
    ver: 5,
    runs7: 318,
    fail7: 1,
    lm: { av: '陳', g: 'green', name: '陳小明', date: '2026/06/10' },
    diagram: [
      { start: true, trig: 'screen', label: '使用者啟動', sub: '商機頁面按鈕' },
      { ic: 'screen', label: '選擇產品與數量' },
      { ic: 'get', label: '取得價目表與折扣規則' },
      { ic: 'screen', label: '確認報價明細' },
      { ic: 'create', label: '建立報價單', sub: 'Quote + QuoteLineItem' },
      { end: true, label: '完成' },
    ],
  },
  {
    name: 'Cisco 保固到期通知',
    api: 'Cisco_Warranty_Expiry',
    trig: 'schedule',
    obj: '排程 · 每日 07:00',
    desc: '每日呼叫 Cisco API 同步保固狀態，對 90 天內到期者建立續約行動項目並通知客戶經理。',
    on: true,
    ver: 1,
    runs7: 7,
    fail7: 5,
    lm: { av: '王', g: 'navy', name: '王淑芬', date: '2026/06/16' },
    diagram: [
      { start: true, trig: 'schedule', label: '每日 07:00', sub: 'Scheduled Flow' },
      { ic: 'action', label: '呼叫 Cisco 保固 API', sub: 'External Service' },
      {
        decision: true,
        label: '90 天內到期？',
        yes: [
          { ic: 'create', label: '建立續約行動項目', sub: 'CallToAction__c' },
          { ic: 'action', label: '通知客戶經理' },
        ],
        no: [{ end: true, label: '結束' }],
      },
    ],
  },
  {
    name: '客戶滿意度調查',
    api: 'CSAT_Survey_OnClose',
    trig: 'screen',
    obj: '服務案件 Case',
    desc: '服務案件結案後彈出滿意度問卷，並將評分寫回案件。目前為草稿，尚未啟用。',
    on: false,
    ver: 1,
    runs7: 0,
    fail7: 0,
    lm: { av: '林', g: 'violet', name: '林雅婷', date: '2026/06/14' },
    diagram: [
      { start: true, trig: 'screen', label: '案件結案後', sub: '草稿 Draft' },
      { ic: 'screen', label: '滿意度問卷', sub: 'CSAT 1–5 分' },
      { ic: 'update', label: '寫回案件評分', sub: 'Case.CSAT__c' },
      { end: true, label: '完成' },
    ],
  },
];
export const FLOW_RUNS: Record<number | 'default', RunEntry[]> = {
  default: [
    {
      ok: 1,
      t: '執行成功',
      d: '處理 1 筆記錄，2 個元素已執行。',
      time: '今天 14:22',
      dur: '0.42s',
    },
    {
      ok: 1,
      t: '執行成功',
      d: '處理 1 筆記錄，2 個元素已執行。',
      time: '今天 11:08',
      dur: '0.39s',
    },
    { ok: 1, t: '執行成功', d: '處理 1 筆記錄。', time: '今天 09:51', dur: '0.51s' },
    { ok: 1, t: '執行成功', d: '處理 1 筆記錄。', time: '昨天 17:30', dur: '0.44s' },
  ],
  1: [
    {
      ok: 0,
      t: '執行失敗',
      d: '動作「送出審核」失敗：找不到提交者的上層主管（Manager 欄位為空）。',
      time: '今天 13:15',
      dur: '0.88s',
    },
    {
      ok: 1,
      t: '執行成功',
      d: '折扣 22% 超限，已送審核給 王淑芬。',
      time: '今天 12:40',
      dur: '0.55s',
    },
    {
      ok: 0,
      t: '執行失敗',
      d: '動作「送出審核」失敗：找不到提交者的上層主管（Manager 欄位為空）。',
      time: '今天 10:02',
      dur: '0.91s',
    },
    { ok: 1, t: '執行成功', d: '折扣 8%，未超限，自動核准。', time: '今天 09:18', dur: '0.33s' },
  ],
  5: [
    {
      ok: 0,
      t: '執行失敗',
      d: '呼叫 Cisco 保固 API 逾時（10s）— External Service「CiscoWarranty」未回應。',
      time: '今天 07:00',
      dur: '10.0s',
    },
    {
      ok: 0,
      t: '執行失敗',
      d: '呼叫 Cisco 保固 API 逾時（10s）。',
      time: '昨天 07:00',
      dur: '10.0s',
    },
    {
      ok: 0,
      t: '執行失敗',
      d: 'HTTP 401 — API 金鑰已過期，請至「系統整合 › API 設定」更新。',
      time: '06/15 07:00',
      dur: '1.2s',
    },
    { ok: 0, t: '執行失敗', d: 'HTTP 401 — API 金鑰已過期。', time: '06/14 07:00', dur: '1.1s' },
  ],
};
export const FLOW_VERSIONS: Record<number | 'default', VerEntry[]> = {
  default: [
    {
      v: '目前版本',
      active: true,
      date: '2026/06/12',
      by: '王淑芬',
      note: '調整通知收件人，新增主管副本。',
    },
    { v: 'v3', active: false, date: '2026/04/30', by: '王淑芬', note: '加入保固產品判斷條件。' },
    { v: 'v2', active: false, date: '2026/02/18', by: '陳小明', note: '初版上線。' },
  ],
  1: [
    {
      v: '目前版本',
      active: true,
      date: '2026/06/15',
      by: '陳小明',
      note: '依角色折扣上限改寫判斷，串接審核流程。',
    },
    { v: 'v6', active: false, date: '2026/05/20', by: '陳小明', note: '新增「已核准」狀態回寫。' },
    { v: 'v5', active: false, date: '2026/03/11', by: '王淑芬', note: '調整審核路由規則。' },
  ],
  5: [
    {
      v: '目前版本',
      active: true,
      date: '2026/06/16',
      by: '王淑芬',
      note: '串接 Cisco 保固 API（External Service）。',
    },
  ],
};

// ── Import Batch 資料 ─────────────────────────────────────────────────────────
export const IMP_SOURCE: Record<ImpSrc, { tag: string }> = {
  csv: { tag: 'CSV 上傳' },
  api: { tag: 'API 同步' },
  manual: { tag: '手動上傳' },
};
export const IMP_STATUS: Record<ImpStatus, { cls: string; lbl: string }> = {
  scheduled: { cls: 'active', lbl: '排程中' },
  processing: { cls: 'proc', lbl: '處理中' },
  completed: { cls: 'active', lbl: '完成' },
  partial: { cls: 'pending', lbl: '部分失敗' },
  failed: { cls: 'inactive', lbl: '失敗' },
  queued: { cls: 'queue', lbl: '排隊中' },
};
export const IMP_RULES = [
  { l: '重複比對欄位', v: 'Email · 統一編號' },
  { l: '重複處理方式', v: '更新既有紀錄（Upsert）' },
  { l: '批次大小', v: '每批 200 筆' },
  { l: '錯誤門檻', v: '失敗 > 10% 自動中止' },
  { l: '預設負責人', v: '依指派規則 / 上傳者' },
  { l: '完成通知', v: 'Email 通知上傳者與管理員' },
];
export const BATCHES: BatchItem[] = [
  {
    name: '每日潛客匯入',
    file: 'leads_daily.csv',
    obj: '名單 Lead',
    src: 'api',
    freq: '排程 · 每日 02:00',
    status: 'scheduled',
    sched: true,
    on: true,
    total: 128,
    ok: 128,
    err: 0,
    skip: 4,
    by: { av: '系', g: 'navy', name: '系統排程', date: '今天 02:00' },
    dur: '14s',
  },
  {
    name: 'ERP 客戶同步',
    file: 'SAP OData',
    obj: '客戶帳號 Account',
    src: 'api',
    freq: '排程 · 每 6 小時',
    status: 'scheduled',
    sched: true,
    on: true,
    total: 42,
    ok: 42,
    err: 0,
    skip: 8,
    by: { av: '系', g: 'navy', name: '系統排程', date: '今天 06:00' },
    dur: '9s',
  },
  {
    name: 'Cisco 保固清單匯入',
    file: 'cisco_warranty_q2.csv',
    obj: '保固續約 Cisco_Warranty_Renewal__c',
    src: 'manual',
    freq: '一次性',
    status: 'processing',
    sched: false,
    on: false,
    total: 1240,
    ok: 794,
    err: 6,
    skip: 0,
    prog: 64,
    by: { av: '王', g: 'navy', name: '王淑芬', date: '今天 14:38' },
    dur: '進行中',
  },
  {
    name: '行銷名單匯入（展會）',
    file: 'expo2026_leads.xlsx',
    obj: '名單 Lead',
    src: 'manual',
    freq: '一次性',
    status: 'completed',
    sched: false,
    on: false,
    total: 560,
    ok: 548,
    err: 0,
    skip: 12,
    by: { av: '林', g: 'violet', name: '林雅婷', date: '昨天 16:20' },
    dur: '31s',
  },
  {
    name: '歷史商機匯入',
    file: 'opps_2024_archive.csv',
    obj: '商機 Opportunity',
    src: 'csv',
    freq: '一次性',
    status: 'partial',
    sched: false,
    on: false,
    total: 312,
    ok: 309,
    err: 3,
    skip: 0,
    by: { av: '陳', g: 'green', name: '陳小明', date: '06/16 11:02' },
    dur: '22s',
  },
  {
    name: '聯絡人批次更新',
    file: 'contacts_update.csv',
    obj: '聯絡人 Contact',
    src: 'csv',
    freq: '一次性',
    status: 'failed',
    sched: false,
    on: false,
    total: 0,
    ok: 0,
    err: 0,
    skip: 0,
    by: { av: '林', g: 'violet', name: '林雅婷', date: '06/16 09:45' },
    dur: '—',
    failReason: '檔案編碼非 UTF-8，且第 1 列標頭與欄位對應不符，匯入未啟動。',
  },
  {
    name: '產品價目表匯入',
    file: 'pricebook_2026h2.csv',
    obj: '產品 Product2',
    src: 'csv',
    freq: '一次性',
    status: 'queued',
    sched: false,
    on: false,
    total: 86,
    ok: 0,
    err: 0,
    skip: 0,
    by: { av: '王', g: 'navy', name: '王淑芬', date: '今天 14:51' },
    dur: '排隊中',
  },
];
export const IMP_ERRORS: Record<number, ImpErrEntry[]> = {
  2: [
    { row: 118, id: 'CSCO-2291', reason: '保固到期日格式錯誤（應為 YYYY-MM-DD）。' },
    { row: 204, id: 'CSCO-2310', reason: '關聯帳號「鴻博科技」查無對應 Account。' },
    { row: 377, id: 'CSCO-2402', reason: 'Cisco 合約號重複，已存在相同紀錄。' },
  ],
  4: [
    { row: 57, id: 'OPP-2024-0571', reason: '金額欄位為空，必填欄位驗證失敗。' },
    { row: 142, id: 'OPP-2024-1183', reason: '階段「Closed」非有效選項清單值。' },
    { row: 288, id: 'OPP-2024-2240', reason: '負責業務 Email 查無對應使用者。' },
  ],
};
export const IMP_MAPPING: Record<number | 'default', MapRow[]> = {
  default: [
    ['name', '名稱', 'Name', 'ok'],
    ['email', 'Email', 'Email', 'ok'],
    ['company', '公司', 'Company', 'ok'],
    ['phone', '電話', 'Phone', 'ok'],
    ['source', '來源', 'LeadSource', 'ok'],
    ['notes', '—', '—', 'skip'],
  ],
  2: [
    ['contract_no', 'Cisco 合約號', 'Cisco_Contract_No__c', 'ok'],
    ['account', '關聯帳號', 'Account__c', 'ok'],
    ['warranty_end', '保固到期日', 'Warranty_End__c', 'ok'],
    ['amount', '續約金額', 'Renewal_Amount__c', 'ok'],
    ['status', '續約狀態', 'Renewal_Status__c', 'ok'],
    ['internal_id', '—', '—', 'skip'],
  ],
  4: [
    ['opp_name', '商機名稱', 'Name', 'ok'],
    ['amount', '金額', 'Amount', 'ok'],
    ['stage', '階段', 'StageName', 'ok'],
    ['close_date', '預計關閉日', 'CloseDate', 'ok'],
    ['owner_email', '負責業務', 'OwnerId', 'ok'],
    ['legacy_note', '—', '—', 'skip'],
  ],
};
export const IMP_RECORDS: Record<number | 'default', ImpRecEntry[]> = {
  default: [
    { id: 'LEAD-0042', name: '張庭瑋 / 宏立科技', status: 'ok' },
    { id: 'LEAD-0043', name: '李孟潔 / 優思資訊', status: 'ok' },
    {
      id: 'LEAD-0044',
      name: '王柏宇 / 鼎新電腦',
      status: 'skip',
      note: '重複 Email — 已 Upsert 更新',
    },
    { id: 'LEAD-0045', name: '陳怡安 / 凱基系統', status: 'ok' },
    { id: 'LEAD-0046', name: '林志豪 / 聯華電子', status: 'ok' },
  ],
  1: [
    { id: 'ACC-1201', name: '宏立科技股份有限公司', status: 'ok' },
    { id: 'ACC-1202', name: '優思資訊有限公司', status: 'ok' },
    { id: 'ACC-1203', name: '鼎新電腦股份有限公司', status: 'ok' },
  ],
  2: [
    { id: 'LEAD-0051', name: '劉怡婷 / 英業達', status: 'ok' },
    { id: 'LEAD-0052', name: '陳冠宏 / 仁寶電腦', status: 'err', note: '缺少必填欄位「公司」' },
    { id: 'LEAD-0053', name: '吳佩儀 / 廣達電腦', status: 'ok' },
    {
      id: 'LEAD-0054',
      name: '黃俊豪 / 和碩聯合',
      status: 'skip',
      note: '重複 Email — 已 Upsert 更新',
    },
    { id: 'LEAD-0055', name: '許雅涵 / 微星科技', status: 'ok' },
  ],
  4: [
    { id: 'OPP-0841', name: '宏立科技-ERP導入案', status: 'ok' },
    { id: 'OPP-0842', name: '優思資訊-雲端續約', status: 'ok' },
    {
      id: 'OPP-0843',
      name: '鼎新電腦-資安方案',
      status: 'err',
      note: '必填欄位「預計關閉日」格式錯誤',
    },
    { id: 'OPP-0844', name: '凱基系統-網路設備採購', status: 'ok' },
  ],
};
